input:
    size: (224,224)
model:
    name: 'mc3_18'
    classes: 3
    pretrained: False 
dataset:
    name: 'CTDataset'
    slice_num: 64
    batch_size: 2
    dir: '/home/datasets/CCCCI_cleaned/dataset_seg'
    train_list: './data/ct_train.json'
    valid_list: './data/ct_test.json'
    test_list: './data/ct_test.json'
    is_train: False
transforms:
    name: 'CTTransforms'
topk: [1,1]
module:
    name: 'CTModule'
hooks:
    early_stopping:
        setting: 2
        patience: 20
        monitor: 'valid_acc_1'
        mode: 'max'
    model_checkpoint:
        setting: 2
        monitor: 'valid_acc_1'
        mode: 'max'
        filepath: ''
trainer:
    min_steps: 99999999
    max_steps: 99999999
